eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: app-items
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true

management:
  security:
    enabled: false