server:
  port: 8089

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: app-web
  cloud:
    config:
      uri: http://localhost:8888
      failFast: true

feign:
  hystrix:
    enabled: true


management:
  security:
    enabled: false